In [11]:
import torch

def EularAngleToMatrix(eularAngle):
    sinEular = eularAngle.sin()
    cosEular = eularAngle.cos()
    matrix = torch.eye(4)

    matrix[0][0] = sinEular[0] * sinEular[1] * sinEular[2] + cosEular[0] * cosEular[2]
    matrix[0][1] = cosEular[1] * sinEular[2] 
    matrix[0][2] = cosEular[0] * sinEular[1] * sinEular[2] - sinEular[0] * cosEular[2]
    matrix[1][0] = sinEular[0] * sinEular[1] * cosEular[2] - cosEular[0] * sinEular[2]
    matrix[1][1] = cosEular[1] * cosEular[2] 
    matrix[1][2] = cosEular[0] * sinEular[1] * cosEular[2] + sinEular[0] * sinEular[2]
    matrix[2][0] = sinEular[0] * cosEular[1]
    matrix[2][1] = -sinEular[1] 
    matrix[2][2] = cosEular[0] * cosEular[1]
    return matrix

def MatrixToEularAngle(matrix):
    eularAngle = torch.zeros(3)

    sinPitch = -matrix[2][1]
    if sinPitch <= -1.0:
        eularAngle[1] = torch.pi * -0.5
    elif sinPitch > 1:
        eularAngle[1] = torch.pi * 0.5
    else:
        eularAngle[1] = torch.asin(sinPitch)

    if torch.abs(sinPitch) >= 0.999999:
        eularAngle[0] = torch.atan2(-matrix[0][2], matrix[0][0])
        eularAngle[2] = 0
    else:
        eularAngle[0] = torch.atan2(matrix[2][0], matrix[2][2])
        eularAngle[2] = torch.atan2(matrix[0][1], matrix[1][1])
        if eularAngle[2] < torch.pi * -0.5 or torch.pi * 0.5 < eularAngle[2]:
            eularAngle[1] = torch.pi - eularAngle[1]
            eularAngle[0] = torch.atan2(-matrix[2][0], -matrix[2][2])
            eularAngle[2] = torch.atan2(-matrix[0][1], -matrix[1][1])
    return eularAngle
 


class ValueNet(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = torch.nn.Linear(3, 3)
        #self.fc2 = torch.nn.Linear(4, 4)

    def forward(self, x):
        x = self.fc1(x)
        #x = torch.nn.functional.relu(self.fc1(x))
        #x = self.fc2(x)
        return x
    
eularAngle = torch.rand(3)
matrix = EularAngleToMatrix(eularAngle)

srcVector = torch.rand((64,3))
#srcVector[:,3]=0
dstVector = torch.matmul(srcVector, matrix[0:3,0:3])
net = ValueNet()
optimizer = torch.optim.Adam(net.parameters(), lr = 1e-2)

epochs = 5000
for epoch in range(epochs):
    yhat = net(srcVector)
    loss = torch.mean(torch.nn.functional.mse_loss(yhat, dstVector))
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    if epoch % 500 ==0:
        print(loss)

mat = net(torch.eye(3))
e  = MatrixToEularAngle(mat)
matrix,mat,eularAngle,e

tensor(1.0279, grad_fn=<MeanBackward0>)
tensor(0.0005, grad_fn=<MeanBackward0>)
tensor(2.8955e-06, grad_fn=<MeanBackward0>)
tensor(6.8574e-09, grad_fn=<MeanBackward0>)
tensor(3.2064e-12, grad_fn=<MeanBackward0>)
tensor(8.0746e-14, grad_fn=<MeanBackward0>)
tensor(4.4116e-14, grad_fn=<MeanBackward0>)
tensor(2.8416e-14, grad_fn=<MeanBackward0>)
tensor(1.3139e-14, grad_fn=<MeanBackward0>)
tensor(8.0042e-15, grad_fn=<MeanBackward0>)


(tensor([[ 0.9000,  0.4090,  0.1506,  0.0000],
         [-0.3363,  0.4317,  0.8370,  0.0000],
         [ 0.2773, -0.8040,  0.5260,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  1.0000]]),
 tensor([[ 0.9000,  0.4090,  0.1506],
         [-0.3363,  0.4317,  0.8370],
         [ 0.2773, -0.8040,  0.5260]], grad_fn=<AddmmBackward0>),
 tensor([0.4852, 0.9339, 0.7585]),
 tensor([0.4852, 0.9339, 0.7585], grad_fn=<CopySlices>))

In [1]:
class Test:
    def __init__(self):
        self.mat3x3 = torch.eye(3, requires_grad=True)
        self.translation = torch.ones(3, requires_grad=True)

    def forward(self, x):
        x = torch.matmul(x, self.mat3x3)+self.translation
        return x
    

eularAngle = torch.rand(3)
matrix = EularAngleToMatrix(eularAngle)
matrix[3,0:3] = torch.rand(3)
srcVector = torch.rand((64,3))
dstVector = torch.matmul(srcVector, matrix[0:3,0:3]) + matrix[3,0:3]
test = Test()
optimizer = torch.optim.Adam([test.mat3x3, test.translation], lr = 1e-2)

epochs = 5000
for epoch in range(epochs):
    yhat = test.forward(srcVector)
    loss = torch.mean(torch.nn.functional.mse_loss(yhat, dstVector))
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    if epoch % 500 ==0:
        print(loss)

matrix, test.mat3x3,test.translation


class Camera:
    def __init__(self, width, height, fovy) -> None:
        self.width = width = width
        self.height = height
        self.fovy = fovy


pixels1 = torch.tensor([
    [870.0, 847.0],
    [2135.0, 512.0],
    [1664.0, 1015.0],
])

pixels1 = torch.tensor([
    [997.0, 878.0],
    [1959.0, 624.0],
    [1601.0, 1007.0],
])

torch.tensor([
    [440.0, 442.0]
    ])


NameError: name 'torch' is not defined